//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopS1_Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryCheckingTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryCheckingTask()
        {
            this.TaskDetail = new HashSet<TaskDetail>();
        }
    
        public int Id { get; set; }
        public string TaskName { get; set; }
        public int WarehouseId { get; set; }
        public int TaskTypeId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int StatusId { get; set; }
    
        public virtual TaskStatus TaskStatus { get; set; }
        public virtual TaskType TaskType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskDetail> TaskDetail { get; set; }
    }
}
